### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by sneakythr0ws** [tbroyer/gradle-errorprone-plugin-v0.0.x#43]
Just added this plugin and got an error
Version 0.0.10, java version "1.8.0_121", gradle 4

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cat-messaging:compileJava'.
> java.lang.reflect.InvocationTargetException

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cat-messaging:compileJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: java.lang.reflect.InvocationTargetException
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:75)
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:24)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:168)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
Caused by: java.lang.reflect.InvocationTargetException
	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:61)
	... 47 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.errorprone.BugCheckerInfo.create(BugCheckerInfo.java:98)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:237)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:266)
	at com.google.errorprone.ErrorProneCompiler$Builder.<init>(ErrorProneCompiler.java:92)
	... 48 more


BUILD FAILED in 0s
13 actionable tasks: 4 executed, 9 up-to-date
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
12:48:18: External tasks execution finished 'clean build --stacktrace '.```

**Comment by tbroyer** [comment]
Check your dependencies (specifically `./gradlew :cat-messaging:dependencies --configuration=errorprone`); you might have some rules that apply to all configurations to force a specific version of Guava that's incompatible with Error Prone. You'd then need to exclude the `errorprone` configuration from that rule.

With Error Prone 2.0.19, Guava should be 21.0.

Here's the output for one of my projects:
```
$ ./gradlew dependencies --configuration=errorprone

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

errorprone
\--- com.google.errorprone:error_prone_core:2.0.19
     +--- com.google.errorprone:error_prone_annotation:2.0.19
     |    \--- com.google.guava:guava:21.0
     +--- com.google.errorprone:error_prone_check_api:2.0.19
     |    +--- com.google.errorprone:error_prone_annotation:2.0.19 (*)
     |    +--- com.google.code.findbugs:jsr305:3.0.0
     |    +--- org.checkerframework:dataflow:1.8.10
     |    |    \--- org.checkerframework:javacutil:1.8.10
     |    +--- com.google.errorprone:javac:9-dev-r3297-4
     |    +--- com.googlecode.java-diff-utils:diffutils:1.3.0
     |    \--- com.google.errorprone:error_prone_annotations:2.0.19
     +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
     +--- org.pcollections:pcollections:2.1.2
     +--- com.google.guava:guava:21.0
     +--- com.google.auto:auto-common:0.7
     |    \--- com.google.guava:guava:19.0 -> 21.0
     +--- com.google.code.findbugs:jFormatString:3.0.0
     +--- com.google.code.findbugs:jsr305:3.0.0
     +--- org.checkerframework:dataflow:1.8.10 (*)
     +--- com.google.errorprone:javac:9-dev-r3297-4
     \--- com.google.errorprone:error_prone_annotations:2.0.19

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

You can also try with `dependencyInsight`:

```
$ ./gradlew dependencyInsight --dependency=guava --configuration=errorprone

> Task :dependencyInsight
com.google.guava:guava:21.0 (conflict resolution)
+--- com.google.errorprone:error_prone_annotation:2.0.19
|    +--- com.google.errorprone:error_prone_core:2.0.19
|    |    \--- errorprone
|    \--- com.google.errorprone:error_prone_check_api:2.0.19
|         \--- com.google.errorprone:error_prone_core:2.0.19 (*)
\--- com.google.errorprone:error_prone_core:2.0.19 (*)

com.google.guava:guava:19.0 -> 21.0
\--- com.google.auto:auto-common:0.7
     \--- com.google.errorprone:error_prone_core:2.0.19
          \--- errorprone

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

Environment:
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.10.0-24-generic amd64
```

**Comment by mrcasablr** [comment]
Hello! 

I have the same error too.  Here is my configuration -

Environment -
```
---------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b12)
OS:           Linux 4.11.7-200.fc25.x86_64 amd64
```
and ..

```
------------------------------------------------------------
Root project
------------------------------------------------------------

errorprone
\--- com.google.errorprone:error_prone_core:2.0.21
     +--- com.google.errorprone:error_prone_annotation:2.0.21
     |    \--- com.google.guava:guava:21.0 -> 18.0
     +--- com.google.errorprone:error_prone_check_api:2.0.21
     |    +--- com.google.errorprone:error_prone_annotation:2.0.21 (*)
     |    +--- com.google.code.findbugs:jsr305:3.0.0
     |    +--- org.checkerframework:dataflow:1.8.10
     |    |    \--- org.checkerframework:javacutil:1.8.10
     |    +--- com.google.errorprone:javac:9-dev-r4023-2
     |    +--- com.googlecode.java-diff-utils:diffutils:1.3.0
     |    +--- com.google.errorprone:error_prone_annotations:2.0.21
     |    \--- com.github.kevinstern:software-and-algorithms:1.0
     +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
     +--- org.pcollections:pcollections:2.1.2
     +--- com.google.guava:guava:21.0 -> 18.0
     +--- com.google.auto:auto-common:0.7
     |    \--- com.google.guava:guava:19.0 -> 18.0
     +--- com.google.code.findbugs:jFormatString:3.0.0
     +--- com.google.code.findbugs:jsr305:3.0.0
     +--- org.checkerframework:dataflow:1.8.10 (*)
     +--- com.google.errorprone:javac:9-dev-r4023-2
     \--- com.google.errorprone:error_prone_annotations:2.0.21

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

I'm using plugin 0.0.10

```
classpath( 'net.ltgt.gradle:gradle-errorprone-plugin:0.0.10' )
```
```
apply plugin: 'net.ltgt.errorprone'
```
```
errorprone 'com.google.errorprone:error_prone_core:2.0.21'
```
```
mrcasablr@localhost api]$ ./gradlew dependencyInsight --dependency=guava --configuration=errorprone

> Task :dependencyInsight
com.google.guava:guava:18.0 (selected by rule)

com.google.guava:guava:19.0 -> 18.0
\--- com.google.auto:auto-common:0.7
     \--- com.google.errorprone:error_prone_core:2.0.21
          \--- errorprone

com.google.guava:guava:21.0 -> 18.0
+--- com.google.errorprone:error_prone_annotation:2.0.21
|    +--- com.google.errorprone:error_prone_core:2.0.21
|    |    \--- errorprone
|    \--- com.google.errorprone:error_prone_check_api:2.0.21
|         \--- com.google.errorprone:error_prone_core:2.0.21 (*)
\--- com.google.errorprone:error_prone_core:2.0.21 (*)

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

**Comment by tbroyer** [comment]
You need to find out which rule forces Guava to version 18, and make sure it doesn't apply to configuration `errorprone`.

**Comment by mrcasablr** [comment]
Thank you! I'm new to Gradle. Is there a easy to figure out which rule is doing this and also how would I skip that rule for errorprone?

**Comment by tbroyer** [comment]
@mrcasablr I'd suggest you ask for assistance on StackOverflow or the Gradle forums; if you didn't setup that rule yourself, then it must come from a plugin; showing your build script (or at a minimum the list of plugins and possibly their configuration) on StackOverflow would probably be enough to diagnose the problem, and hopefully find a solution. Feel free to post the link here once you asked there.

@vnikolaenko Any news on your side?

**Comment by sneakythr0ws** [comment]
Hi! I have same situation as @mrcasablr .

But I found temporary solution
```
	configurations.errorprone {
		resolutionStrategy {
			dependencySubstitution {
				substitute module('com.google.guava:guava') with module('com.google.guava:guava:21.0')
			}
		}
	}
```

**Comment by tbroyer** [comment]
Thanks for the update.
