### ISSUE TITLE
JDK 8 support

### ISSUE THREAD

**Issue by yogurtearl** [tbroyer/gradle-errorprone-plugin-v0.0.x#5]
The gradle error prone plugin seems to have issues with JDK 8u11

Caused by: java.lang.RuntimeException
    at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:87)
    at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:33)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:24)
    at org.gradle.api.tasks.compile.Compile.performCompilation(Compile.java:165)
    at org.gradle.api.tasks.compile.Compile.compile(Compile.java:153)
    at org.gradle.api.tasks.compile.Compile.compile(Compile.java:87)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:236)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:223)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 66 more
Caused by: java.lang.reflect.InvocationTargetException
    at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:85)
    ... 81 more
Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.main.Main.compile([Ljava/lang/String;Lcom/sun/tools/javac/util/Context;Lcom/sun/tools/javac/util/List;Ljava/lang/Iterable;)I
    at com.google.errorprone.JDK7Shim.runCompile(JDK7Shim.java:62)
    at com.google.errorprone.JDKCompatible.runCompile(JDKCompatible.java:94)
    at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:171)
    at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:134)
    at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:124)
    ... 82 more

**Comment by yogurtearl** [comment]
May be related to https://code.google.com/p/error-prone/issues/detail?id=246

**Comment by tbroyer** [comment]
See also #1

**Comment by tbroyer** [comment]
Looks like errorprone 1.1.3 will have this fixed.

**Comment by tbroyer** [comment]
Small update: due to what's been deployed to Central, errorprone 1.x will only ever support JDK 7. I've updated `master` to be compatible with the recently-released errorprone 2.0, which supports both JDK 7 and JDK 8 (uses it's own JDK 8 compiler in both cases).
