### ISSUE TITLE
Support gradle 4.3

### ISSUE THREAD

**Issue by azell** [tbroyer/gradle-errorprone-plugin-v0.0.x#53]
```
$ gradle --version

------------------------------------------------------------
Gradle 4.3
------------------------------------------------------------

Build time:   2017-10-30 15:43:29 UTC
Revision:     c684c202534c4138b51033b52d871939b8d38d72

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.13 x86_64
```

**Comment by JakeWharton** [comment]
What's the problem? Works fine here.

**Comment by tbroyer** [comment]
Same here, now tested in 22c3bc4b5cc10edd2fb2cb669f3fea0ca6b86d1b, didn't need any code change.

**Comment by ZacSweers** [comment]
I get this on 4.3.1 with 0.0.13:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.ltgt.gradle.apt.CompatibilityUtils
        at net.ltgt.gradle.apt.AptPlugin$5.execute(AptPlugin.java:173)
        at net.ltgt.gradle.apt.AptPlugin$5.execute(AptPlugin.java:169)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
       ........... rest of the gradle trace during configuration
```

**Comment by tbroyer** [comment]
Wrong project; you'll want https://github.com/tbroyer/gradle-apt-plugin. Also, you're not using the latest version (line numbers don't match); Gradle 4.3 needs 0.13.

**Comment by ZacSweers** [comment]
Eesh, I can't read -_-. Sorry!
