### ISSUE TITLE
error prone doesn't fix the upstream version of guava

### ISSUE THREAD

**Issue by xenoterracide** [tbroyer/gradle-errorprone-plugin-v0.0.x#58]
so here's the error I ran into, TL;DR; it's getting the wrong version of guava
```
$ ./gradlew clean build --stacktrace --info
Initialized native services in: C:\Users\xeno\.gradle\native
The client will now receive all logging from the daemon (pid: 8164). The daemon log file: C:\Users\xeno\.gradle\daemon\4.4\daemon-8164.out.log
Starting 25th build in daemon [uptime: 13 mins 47.925 secs, performance: 99%, no major garbage collections]
Using 4 worker leases.
Creating new cache for fileHashes, path C:\Users\xeno\IdeaProjects\entity-api\.gradle\4.4\fileHashes\fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@780c4d58
Starting Build
Settings evaluated using settings file 'C:\Users\xeno\IdeaProjects\entity-api\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\xeno\IdeaProjects\entity-api\build.gradle'.
Included projects: [root project 'entity-api']

> Configure project :
Evaluating root project 'entity-api' using build file 'C:\Users\xeno\IdeaProjects\entity-api\build.gradle'.
Creating new cache for metadata-1.1/results, path C:\Users\xeno\.gradle\caches\transforms-1\metadata-1.1\results.bin, access org.gradle.cache.internal.DefaultCacheAccess@2547d854
Creating new cache for metadata-2.36/module-metadata, path C:\Users\xeno\.gradle\caches\modules-2\metadata-2.36\module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@64618df
Creating new cache for metadata-2.36/module-artifacts, path C:\Users\xeno\.gradle\caches\modules-2\metadata-2.36\module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@64618df
Creating new cache for metadata-2.36/module-versions, path C:\Users\xeno\.gradle\caches\modules-2\metadata-2.36\module-versions.bin, access org.gradle.cache.internal.DefaultCacheAccess@64618df
Creating new cache for metadata-2.36/module-artifact, path C:\Users\xeno\.gradle\caches\modules-2\metadata-2.36\module-artifact.bin, access org.gradle.cache.internal.DefaultCacheAccess@64618df
Applying dependency management to configuration 'api' in project 'entity-api'
Applying dependency management to configuration 'apiElements' in project 'entity-api'
Applying dependency management to configuration 'archives' in project 'entity-api'
Applying dependency management to configuration 'compile' in project 'entity-api'
Applying dependency management to configuration 'compileClasspath' in project 'entity-api'
Applying dependency management to configuration 'compileOnly' in project 'entity-api'
Applying dependency management to configuration 'default' in project 'entity-api'
Applying dependency management to configuration 'errorprone' in project 'entity-api'
Applying dependency management to configuration 'implementation' in project 'entity-api'
Applying dependency management to configuration 'runtime' in project 'entity-api'
Applying dependency management to configuration 'runtimeClasspath' in project 'entity-api'
Applying dependency management to configuration 'runtimeElements' in project 'entity-api'
Applying dependency management to configuration 'runtimeOnly' in project 'entity-api'
Applying dependency management to configuration 'spotbugs' in project 'entity-api'
Applying dependency management to configuration 'spotbugsPlugins' in project 'entity-api'
Applying dependency management to configuration 'testCompile' in project 'entity-api'
Applying dependency management to configuration 'testCompileClasspath' in project 'entity-api'
Applying dependency management to configuration 'testCompileOnly' in project 'entity-api'
Applying dependency management to configuration 'testImplementation' in project 'entity-api'
Applying dependency management to configuration 'testRuntime' in project 'entity-api'
Applying dependency management to configuration 'testRuntimeClasspath' in project 'entity-api'
Applying dependency management to configuration 'testRuntimeOnly' in project 'entity-api'
Applying dependency management to configuration 'checkstyle' in project 'entity-api'

All projects evaluated.
Selected primary task 'clean' from project :
Selected primary task 'build' from project :
Creating new cache for annotation-processors, path C:\Users\xeno\IdeaProjects\entity-api\.gradle\4.4\fileContent\annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@17f8ad87
Tasks to be executed: [task ':clean', task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':assemble', task ':checkstyleMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':spotbugsMain', task ':spotbugsTest', task ':test', task ':check', task ':build']
Creating new cache for resourceHashesCache, path C:\Users\xeno\IdeaProjects\entity-api\.gradle\4.4\fileHashes\resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@780c4d58
Invalidating in-memory cache of C:\Users\xeno\IdeaProjects\entity-api\.gradle\4.4\fileHashes\resourceHashesCache.bin
Creating new cache for taskHistory, path C:\Users\xeno\IdeaProjects\entity-api\.gradle\4.4\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@211d5b85
Creating new cache for outputFiles, path C:\Users\xeno\IdeaProjects\entity-api\.gradle\buildOutputCleanup\outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@10e9e558
:clean (Thread[Daemon worker Thread 4,5,main]) started.

> Task :clean
Putting task artifact state for task ':clean' into context took 0.0 secs.
Up-to-date check for task ':clean' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.

:clean (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.013 secs.
:compileJava (Thread[Task worker for ':' Thread 3,5,main]) started.
Download https://d3vfm0n2cffdwd.cloudfront.net/com/google/errorprone/error_prone_core/maven-metadata.xml
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_core/maven-metadata.xml

> Task :compileJava FAILED
Putting task artifact state for task ':compileJava' into context took 0.0 secs.
Resolving global dependency management for project 'entity-api'
Excluding [commons-logging:commons-logging]
Up-to-date check for task ':compileJava' took 0.332 secs. It is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':compileJava'.
Compiling with error-prone compiler
Creating new cache for metadata-2.36/resource-at-url, path C:\Users\xeno\.gradle\caches\modules-2\metadata-2.36\resource-at-url.bin, access org.gradle.cache.internal.DefaultCacheAccess@64618df
Excluding []

:compileJava (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 1.747 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.reflect.InvocationTargetException

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: java.lang.reflect.InvocationTargetException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:69)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:23)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:192)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:124)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: java.lang.reflect.InvocationTargetException
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:60)
        ... 49 more
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;
        at com.google.errorprone.BugCheckerInfo.customSuppressionAnnotations(BugCheckerInfo.java:144)
        at com.google.errorprone.BugCheckerInfo.<init>(BugCheckerInfo.java:122)
        at com.google.errorprone.BugCheckerInfo.create(BugCheckerInfo.java:110)
        at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:298)
        at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:291)
        at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:327)
        at com.google.errorprone.ErrorProneCompiler$Builder.<init>(ErrorProneCompiler.java:91)
        ... 50 more


* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 2 executed
```

why is it getting the wrong version of guava? I'm pretty sure it's spring platform bom.

```
import com.github.spotbugs.SpotBugsTask
/*
 * This build file was generated by the Gradle 'init' task.
 *
 * This generated file contains a commented-out sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.3/userguide/tutorial_java_projects.html
 */
buildscript {
    repositories {
        maven {
            url System.getenv('JAR_REPOSITORY_URI')
        }
        jcenter()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:latest.release'
    }
}

plugins {
    id 'com.github.spotbugs' version '1.6.0'
    id 'net.ltgt.errorprone' version '0.0.13'
}

repositories {
    maven {
        url System.getenv('JAR_REPOSITORY_URI')
    }
    jcenter()
}


group 'com.xenoterracide'
version '0.1.0-SNAPSHOT'

// Apply the java plugin to add support for Java
apply plugin: 'java-library'
apply plugin: 'idea'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'checkstyle'
apply plugin: 'com.github.spotbugs'
apply plugin: 'maven-publish'


dependencyManagement {
    imports {
        mavenBom 'com.xenoterracide:bom:0.1.0-SNAPSHOT'
    }
}

// In this section you declare the dependencies for your production and test code
dependencies {
    errorprone 'com.google.errorprone:error_prone_core:latest.release'  // 2.1.x
```

simply forcing guava to version 22.0 as such, fixes the issue

```
    errorprone 'com.google.guava:guava:22.0'
    errorprone 'com.google.errorprone:error_prone_core:latest.release'
```

however I have a few questions, concerns and the reason I'm writing this in the first place

1. will this updated dependency for error prone change the guava version for any of my actual work? e.g. will guava then be 22.0 for the whole project?
1. is there anything that can be done in this plugin to force a lockin that for sure won't leak?
1. can this sort of scenario be added to the readme?
1. is there anything that I could send to to the spring dependency management plugin writers that they could do? I don't expect them to fix their guava version, but perhaps there's a way of specifying this dependency in a way that they'll know not to override (though I suspect unless it was obvious they wouldn't)

**Comment by tbroyer** [comment]
> will this updated dependency for error prone change the guava version for any of my actual work? e.g. will guava then be 22.0 for the whole project?

No, that's the _raison d'être_ of Gradle configurations.

> is there anything that can be done in this plugin to force a lockin that for sure won't leak?

I don't think so.
As you identified, the problem is that you're using another plugin that overrides the default dependency resolution for all configurations, including those used for tools.
You'd have to somehow configure that other plugin such that it ignores the `errorprone` configuration.

> can this sort of scenario be added to the readme?

Well, I could, but there are so many ways to screw your configuration. I'll see what I can do.

> is there anything that I could send to to the spring dependency management plugin writers that they could do? I don't expect them to fix their guava version, but perhaps there's a way of specifying this dependency in a way that they'll know not to override (though I suspect unless it was obvious they wouldn't)

To the spring dependency management plugin, ask for a way to exclude some configurations from the global configuration; or make it easy to configure "all configurations but X". For now, I suppose that configuring the `compileClasspath`, `runtimeClasspath`, `testCompileClasspath` and `testRuntimeClasspath` could be enough.

Now for the Guava version, it comes from your `com.xenoterracide:bom:0.1.0-SNAPSHOT`…

**Comment by xenoterracide** [comment]
> Well, I could, but there are so many ways to screw your configuration. I'll see what I can do.

yes, I guess it just wan't obvious to me that I could set the guava version as a dependency of the plugin by setting it with the `errorprone`, at least not at first, nor being new to gradle what the consequence of that would be. Obviously I don't expect you to be able to cover every possible library foobar, maybe just some brief section explaining how to override a dependency for a situation like this, as I basically just guessed after several hours of banging my head.

>    Now for the Guava version, it comes from your com.xenoterracide:bom:0.1.0-SNAPSHOT…

yes, that's just an extension of spring platform bom, with a couple of other versions added

Thanks for answering my questions, I'll hit up the spring bom people later today.

**Comment by kartoffelsup** [comment]
Hi, 
not sure if my issue is the same/similar to this but it might be close enough to post the repro repo here:
https://github.com/kartoffelsup/example-error-prone-guava

I'm trying to use `error-prone` with `JDK9` and `guava:23.5-jre`. Running `gradlew build` results in 
```
> Task :lib:compileJava FAILED
F:\dev\error-prone-guava\lib\src\main\java\module-info.java:2: error: module not found: com.google.common
  requires com.google.common;
                     ^
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.
```
Which works fine without error-prone

**Comment by xenoterracide** [comment]
that error looks like it requires the java 9 jigsaw --add-module, thought I'm not sure how to do that in this configuration

**Comment by kartoffelsup** [comment]
Okay, it seems like this is more just a missing feature/bug in error-prone itself, since the same error appears with different libraries I've tried as well (gson, commons-lang3).

**Comment by tbroyer** [comment]
I haven't tried but I'm not sure Error Prone actually fully supports JPMS. In any case, that's a different issue (and I'd say one with Error Prone itself then)

**Comment by tbroyer** [comment]
Added new troubleshooting steps to the README for the dependency configuration issue (fe82bd7be890bd6b2ba9f48c62b37b55911b4785)

**Comment by xenoterracide** [comment]
is it possible you could add something to the effect of

you can override the overridden dependency by adding another errorprone scoped dependency, for example
```
    errorprone "com.google.guava:guava:latest.release"
    errorprone "com.google.errorprone:error_prone_core:latest.release"
```
