### ISSUE TITLE
JDK8 + errorprone-1.3-SNAPSHOT = ClassCastException

### ISSUE THREAD

**Issue by ben-manes** [tbroyer/gradle-errorprone-plugin-v0.0.x#6]
The return value of the compiler (ErrorProneCompiler.java:57) was changed from an int to an enum in Java 8 with an `exitCode` field. See the OpenJDK [source](http://hg.openjdk.java.net/jdk8u/jdk8u40/langtools/file/c3d6d1a53399/src/share/classes/com/sun/tools/javac/main/Main.java).

**Comment by tbroyer** [comment]
Fixed in `master`.

**Comment by ben-manes** [comment]
Thanks!

**Comment by ben-manes** [comment]
P.S. You should validate against Gradle 2.3-rc-1 prior to release

**Comment by ben-manes** [comment]
`0.0.6-SNAPSHOT` is not available in the Sonatype snapshots repository. By listing it in the README implies that it is, vs saying on `master`

**Comment by tbroyer** [comment]
I had failures with oss.sonatype.org earlier today, should be OK now.

**Comment by ben-manes** [comment]
Thanks, [works perfectly](https://github.com/ben-manes/caffeine/commit/2143f294bf0e1ec32ff65b6cc47691bda1ed7b7f).

**Comment by xenoterracide** [comment]
according to intellij ErrorProneOptions.class doesn't exist for me... can't compile that.

**Comment by xenoterracide** [comment]
ok, I fixed that but, it's still leaving me at this exception

```
com.xenoterracide.gradle.plugin.XenoPluginTest > codeQuality(Collection)[1] FAILED
    org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'net.ltgt.gradle.errorprone.ErrorPronePlugin']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at com.xenoterracide.gradle.plugin.configurations.ErrorProneSharedConfig.apply(ErrorProneSharedConfig.java:39)
        at com.xenoterracide.gradle.plugin.configurations.ErrorProneSharedConfig.apply(ErrorProneSharedConfig.java:35)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
        at com.xenoterracide.gradle.plugin.XenoCodeQualityPlugin.apply(XenoCodeQualityPlugin.java:44)
        at com.xenoterracide.gradle.plugin.XenoCodeQualityPlugin.apply(XenoCodeQualityPlugin.java:36)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
        at com.xenoterracide.gradle.plugin.XenoPluginTest.codeQuality(XenoPluginTest.java:66)

        Caused by:
        org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'ErrorPronePlugin'.
            at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:79)
            at org.gradle.api.internal.plugins.DefaultPluginManager.producePluginInstance(DefaultPluginManager.java:193)
            at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:169)
            at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
            at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
            at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
            at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
            at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
            ... 38 more

            Caused by:
            java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
                at net.ltgt.gradle.errorprone.ErrorPronePlugin.<clinit>(ErrorPronePlugin.kt:43)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:65)
                at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:77)
                ... 51 more

                Caused by:
                java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
                    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
                    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                    ... 58 more



com.xenoterracide.gradle.plugin.XenoPluginTest > codeQuality(Collection)[2] FAILED
    org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'net.ltgt.gradle.errorprone.ErrorPronePlugin']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at com.xenoterracide.gradle.plugin.configurations.ErrorProneSharedConfig.apply(ErrorProneSharedConfig.java:39)
        at com.xenoterracide.gradle.plugin.configurations.ErrorProneSharedConfig.apply(ErrorProneSharedConfig.java:35)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.xenoterracide.gradle.plugin.XenoCodeQualityPlugin.apply(XenoCodeQualityPlugin.java:44)
        at com.xenoterracide.gradle.plugin.XenoCodeQualityPlugin.apply(XenoCodeQualityPlugin.java:36)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:134)
        at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
        at com.xenoterracide.gradle.plugin.XenoPluginTest.codeQuality(XenoPluginTest.java:66)

        Caused by:
        org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'ErrorPronePlugin'.
            at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:79)
            at org.gradle.api.internal.plugins.DefaultPluginManager.producePluginInstance(DefaultPluginManager.java:193)
            at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:169)
            at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
            at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
            at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
            at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
            at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
            ... 38 more

            Caused by:
            java.lang.NoClassDefFoundError: Could not initialize class net.ltgt.gradle.errorprone.ErrorPronePlugin
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:65)
                at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:77)
                ... 51 more

````

**Comment by xenoterracide** [comment]
alright, I tried your suggestions, no dice, https://bitbucket.org/xenoterracide/gradle-plugin-bundle/addon/pipelines/home#!/results/158/steps/%7B86c2e1eb-6edb-4401-8549-6a3ea77109e7%7D/test-report since my project is open source, would you mind trying to implement a patch for it? maybe I'm doing something wrong. here's a link to the branch diff https://bitbucket.org/xenoterracide/gradle-plugin-bundle/branch/ep#diff

**Comment by tmack8001** [comment]
so what is the solution to this? When I switch from 0.0.x -> 0.6 I get the same exact error. I'm using the groovy version of build.gradle and not the kotlin version.

**Comment by xenoterracide** [comment]
I would suggest commenting on the upstream bug, its' not getting enough love
